// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onrslzaubwvbgfzjjlio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucnNsemF1Ynd2YmdmempqbGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzQzMDMsImV4cCI6MjA2MzYxMDMwM30.AtSFAuWmRgzqaFGKVSjr1qlh65h_Y9qY8fZvODGVqKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);